---
title: Event Access Control (access field)
---

# Event Access Control (`access` field)

The `access` field within the Semantic Event Schema is a nested structure designed to define rules that govern who is permitted or denied access to view, process, or analyze an event. This facility is crucial for implementing data governance, upholding privacy controls (e.g., GDPR compliance), and ensuring that events are only exposed to authorized users, organizations, or systems.

When an event has access control rules defined, its `access` field will typically contain a list (array) of rule objects. Each object in this list specifies a condition under which access is either granted (whitelisted) or denied (blacklisted).

## Access Rule Object Properties

The following table details the fields found within each object in the `access` list:

| Name               | Required | Data Type | Description                                                                                                                                                                                             |
|--------------------|----------|-----------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| `type`             |          | `String`  | The type of access rule. Allowed values are: <br/> - `"Blacklisted"` (1): Denies access if the conditions match. <br/> - `"Whitelisted"` (2): Grants access if the conditions match. (From SQL Enum8) |
| `label`            |          | `String`  | A human-readable label or description for this access rule (e.g., "Exclude Test Users", "Partner Org Access Q1-2024"). Originally `LowCardinality(String)`.                                             |
| `user_gid`         |          | `UUID`    | The Global ID (GID) of a specific user to whom this rule applies.                                                                                                                                       |
| `organization_gid` |          | `UUID`    | The Global ID (GID) of an organization to which this rule applies. If present, the rule targets users within this organization. This field is optional.                                                  |
| `date_from`        |          | `Timestamp` | The date and time (UTC) from which this access rule becomes effective. If null, the rule is effective immediately or from the start of time. This field is optional.                                     |
| `date_to`          |          | `Timestamp` | The date and time (UTC) until which this access rule is effective. If null, the rule remains effective indefinitely. This field is optional.                                                             |

## Understanding and Applying Access Rules

The `access` structure provides the necessary metadata for systems to make decisions about event visibility and processing. The actual enforcement logic (e.g., whether the default policy is to deny all unless explicitly whitelisted, or to allow all unless explicitly blacklisted) depends on the consuming system's implementation and overall data governance policies.

**General Principles:**

*   **Specificity:** Rules can target individual users (`user_gid`) or all users within a specific organization (`organization_gid`). If both are present, it typically implies the rule applies to that specific user *within* that organization.
*   **Time-Bound Access:** The `date_from` and `date_to` fields allow for creating temporary access permissions or restrictions, useful for projects, audits, or collaborations with fixed durations.
*   **Multiple Rules:** An event can have multiple access rules. Consuming systems must evaluate all relevant rules according to their defined precedence and policy (e.g., a blacklist rule for a user might override a whitelist rule for their organization).
*   **`label` for Clarity:** The `label` field is important for manageability, allowing administrators to understand the purpose of each rule without deciphering GIDs alone.

**Use-Case Examples:**

1.  **Blacklisting a Test User's Events from Production Analytics:**
    Prevent events generated by a specific internal test user from appearing in production dashboards or being processed by certain downstream systems.
    *   An `access` object might be:
        ```json
        {
          "type": "Blacklisted",
          "label": "Internal Test User Data - Exclude from Production Analytics",
          "user_gid": "user-uuid-test-alpha"
          // organization_gid, date_from, date_to might be null or not applicable
        }
        ```

2.  **Whitelisting Events for a Specific Partner Organization:**
    Allow only users belonging to a specific partner organization to access events that are relevant to that partnership.
    *   An `access` object might be:
        ```json
        {
          "type": "Whitelisted",
          "label": "Partner XYZ Corp Access - Q2 Campaign Data",
          "organization_gid": "org-uuid-partner-xyz",
          "date_from": "2024-04-01T00:00:00Z",
          "date_to": "2024-06-30T23:59:59Z"
        }
        ```
    *(Note: In this whitelisting scenario, the `user_gid` field would still be present in the actual data structure, often set to a specific system user or a wildcard representation if the SQL schema doesn't allow NULL for it and the rule is meant for any user in that org. However, for conceptual clarity in a whitelist-by-org, the `organization_gid` is the primary driver.)* The Avro schema indicates `user_gid` is required. For an org-wide rule, it might be a GID of a system principal representing "any authenticated user in org X".

3.  **Time-Restricted Access for a Contractor:**
    Grant a specific contractor (identified by `user_gid`) access to certain types of events only for the duration of their contract.
    *   An `access` object might be:
        ```json
        {
          "type": "Whitelisted",
          "label": "Contractor Jane Doe - Project Phoenix Access",
          "user_gid": "user-uuid-contractor-jane",
          "date_from": "2024-01-15T00:00:00Z",
          "date_to": "2024-07-15T23:59:59Z"
        }
        ```

By utilizing the `access` structure, organizations can implement granular control over their event data, ensuring that sensitive information is protected and that users only see data relevant and permitted to them, thereby supporting compliance with privacy regulations and internal data governance policies.
